name: workflow-test

on:
  push:
    branches:
      - '**'
  pull_request:
    branches:
      - master

jobs:
  workflow-test:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 16

      - name: install client dependencies
        run: |
          cd ./client 
          npm ci

      - name: test client
        run: |
          cd ./client 
          npm run test

      - name: install server dependencies
        run: |
          cd ./server 
          go get ./...

      - name: test server
        run: |
          cd ./server
          go test ./... -v
        env:
          CLIENT_LINK: ${{ secrets.CLIENT_LINK }}
          DATABASE_HOST: ${{ secrets.DATABASE_HOST }}
          DATABASE_PORT: ${{ secrets.DATABASE_PORT }}
          DATABASE_USER: ${{ secrets.DATABASE_USER }}
          DATABASE_PASS: ${{ secrets.DATABASE_PASS }}
          DATABASE_NAME: ${{ secrets.DATABASE_NAME }}
          DATABASE_SSLMODE: ${{ secrets.DATABASE_SSLMODE }}
          EMAIL_USER: ${{ secrets.EMAIL_USER }}
          EMAIL_PASS: ${{ secrets.EMAIL_PASS }}
